version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: monthly
    time: "07:07"
    timezone: US/Central
  open-pull-requests-limit: 10
  assignees:
  - mreishus
  ignore:
  - dependency-name: credo
    versions:
    - 1.5.4
  - dependency-name: phoenix
    versions:
    - 1.5.7
  - dependency-name: ecto_sql
    versions:
    - 3.5.3
  - dependency-name: postgrex
    versions:
    - 0.15.7
- package-ecosystem: npm
  directory: "/apps/demon_spirit_web/assets"
  schedule:
    interval: monthly
    time: "07:07"
    timezone: US/Central
  open-pull-requests-limit: 10
  assignees:
  - mreishus
  ignore:
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.3
    - 1.3.5
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: css-loader
    versions:
    - 5.0.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "07:07"
    timezone: US/Central
  open-pull-requests-limit: 10
  assignees:
  - mreishus
  ignore:
  - dependency-name: alpine
    versions:
    - 3.12.3
    - 3.13.1
  - dependency-name: elixir
    versions:
    - 1.11.2.pre.alpine
